version: "3.3"

services: 
  database:
    image: postgres
    network_mode: "host"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "demo"
      POSTGRES_PASSWORD: "postgres"
  api-token: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    network_mode: "host"