version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    network_mode: "host"
  api-token:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: "host"
    volumes:
      - ./:/app
