version: "3.3"

services: 
  redis_container:
    container_name: redis-app
    ports: 
      - "6379:6379"
    image: redis
  api_container:
    container_name: api-app
    ports: 
      - "3000:3000"
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    depends_on: 
      - redis_container
    